#!/usr/bin/env bash
function log(){
    local info_prefix="\e[32m[INFO]\e[0m: ";
    local warn_prefix="\e[33m[WARN]\e[0m: ";
    local error_prefix="\e[31m[ERROR]\e[0m: ";
    local time=$(date +"%Y-%m-%d %X %z");

    if [ "$1" == INFO ]; then
       echo -e $info_prefix $2;
       echo -e "["$time"] " $@ >>log.log;
    elif [ "$1" == INFO_s ]; then
       echo -e "["$time"] " $@ >>log.log;
    elif [ "$1" == ERROR ]; then
        echo -e $error_prefix $2;
        echo -e "["$time"] " $@ >>log.log;
    elif [ "$1" == WARN ]; then
        echo -e $warn_prefix $2;
        echo -e "["$time"] " $@ >>log.log;

    elif [ "$1" == STARS ]; then
        echo -e "\n* * *\n";
    else
        echo -e "\n";
    fi;
}

function selectYN(){
	select yesno in "Yes" "No"
	do
	    log INFO_s "'$yesno' has been selected";
		if [ "$yesno" = No ]; then
		    exit 1;
		elif [ "$yesno" = Yes ]; then
		    exit 0;
		else log WARN "Yes/No?";
		fi;
	done;
}